# Name of the github action
name: Stats

# This part works to know when it will execute the github action
on:

# Always on push
  push:
    branches: [ "main" ]

# Here it indicates the jobs to do
jobs:

# build your code
  build:

    runs-on: ubuntu-latest

    steps:

    # Checkout repo
    - name: Checkout repo
      uses: actions/checkout@v4
      
    # Build
    - name: Build
      run: make

    # Run program
    - name: Run program
      run: ./program

    
